Cosmetic and quality of life changes
alexxRT/riscv64-simulator pull request #11
Opened 2024-11-13 14:47 UTC by vian96

- moved all work from current main to test functions, after which there is output if everything was okay
- added script for compiling to rv64i (just call `asmcompile.sh`)
- changed EXIT pseudoinstruction handling to proper one

2024-11-13 14:51 UTC, nerett commented
Maybe integrate with #10

2024-11-15 13:10 UTC, nerett requested changes

2024-11-15 13:10 UTC, nerett commented on asmcompile.sh
please delete

2024-11-19 20:11 UTC, vian96 commented on asmcompile.sh
done

2024-11-19 20:21 UTC, nerett approved these changes

2024-11-19 21:18 UTC, vian96 commented
got one approve => merging

2024-11-19 21:19 UTC, merged